version: '1.2.{build}.0'
image: Visual Studio 2019

configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
  nuget restore SevenZip.sln

environment:
  COVERALLS_REPO_TOKEN:  
    secure: 9nrrklS2VRyutuqp/K8xVrv8bD+rRW5HgjWJ670wirR74AgvGOd5qnwTIFWHZBEx

build:
  parallel: true
  project: 'SevenZip.sln'
  publish_nuget: false

after_build:
  - cmd: nuget pack package.nuspec -version "%APPVEYOR_BUILD_VERSION%"

after_test:
  - ps: Invoke-Expression ($env:USERPROFILE + '\.nuget\packages\OpenCover\4.7.922\tools\OpenCover.Console.exe -register:Path64 -filter:"+[*]* -[SevenZip.Tests]* -[nunit.framework]*" -target:"' + $env:USERPROFILE + '\.nuget\packages\nunit.consolerunner\3.10.0\tools\nunit3-console.exe" -targetargs:"/domain:single Stage/Release/net45/SevenZip.Tests.dll" -output:coverage.xml')
  - ps: Invoke-Expression ($env:USERPROFILE + '\.nuget\packages\coveralls.io.\1.4.2\tools\coveralls.net.exe --opencover "coverage.xml" -r %COVERALLS_REPO_TOKEN%')

artifacts:
  - path: 'Squid-Box.SevenZip*.nupkg'
    name: NuGet

  - path: 'coverage.xml'
    name: Code Coverage

deploy:
  - provider: NuGet
    api_key:
      secure: Prw8zFhOF/86T5reyuCU+NIfxXPUpFHOljuKnlxeA4MrHuVm1QeAMF3Tq7R99bmP
    artifact: /SevenZip.*\.nupkg/
    skip_symbols: false
    on:
      branch: master
